# Generated by Django 4.2.3 on 2023-07-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='day',
            options={},
        ),
        migrations.AddField(
            model_name='task',
            name='tasks',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
