# Generated by Django 4.2.3 on 2023-07-24 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collectorapp', '0002_alter_course_options_alter_day_options_task_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courses',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tasks',
            new_name='Task',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectorapp.course')),
                ('d_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', smart_selects.db_fields.ChainedForeignKey(chained_field='Course', chained_model_field='Course', on_delete=django.db.models.deletion.CASCADE, to='collectorapp.task', verbose_name='Task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
